// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet1.proto

package next.net.netty.test.proto;

public final class Packet1Wapper {
  private Packet1Wapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Packet1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 playerId = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>optional int32 money = 2;</code>
     */
    int getMoney();

    /**
     * <code>optional int64 time = 4;</code>
     */
    long getTime();

    /**
     * <code>optional bool vip = 3;</code>
     */
    boolean getVip();
  }
  /**
   * Protobuf type {@code Packet1}
   */
  public  static final class Packet1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet1)
      Packet1OrBuilder {
    // Use Packet1.newBuilder() to construct.
    private Packet1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet1() {
      playerId_ = 0;
      money_ = 0;
      time_ = 0L;
      vip_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Packet1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerId_ = input.readInt32();
              break;
            }
            case 16: {

              money_ = input.readInt32();
              break;
            }
            case 24: {

              vip_ = input.readBool();
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return next.net.netty.test.proto.Packet1Wapper.internal_static_Packet1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return next.net.netty.test.proto.Packet1Wapper.internal_static_Packet1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              next.net.netty.test.proto.Packet1Wapper.Packet1.class, next.net.netty.test.proto.Packet1Wapper.Packet1.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>optional int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int MONEY_FIELD_NUMBER = 2;
    private int money_;
    /**
     * <code>optional int32 money = 2;</code>
     */
    public int getMoney() {
      return money_;
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>optional int64 time = 4;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int VIP_FIELD_NUMBER = 3;
    private boolean vip_;
    /**
     * <code>optional bool vip = 3;</code>
     */
    public boolean getVip() {
      return vip_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0) {
        output.writeInt32(1, playerId_);
      }
      if (money_ != 0) {
        output.writeInt32(2, money_);
      }
      if (vip_ != false) {
        output.writeBool(3, vip_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (money_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, money_);
      }
      if (vip_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, vip_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof next.net.netty.test.proto.Packet1Wapper.Packet1)) {
        return super.equals(obj);
      }
      next.net.netty.test.proto.Packet1Wapper.Packet1 other = (next.net.netty.test.proto.Packet1Wapper.Packet1) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && (getMoney()
          == other.getMoney());
      result = result && (getTime()
          == other.getTime());
      result = result && (getVip()
          == other.getVip());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + VIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVip());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static next.net.netty.test.proto.Packet1Wapper.Packet1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(next.net.netty.test.proto.Packet1Wapper.Packet1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet1)
        next.net.netty.test.proto.Packet1Wapper.Packet1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return next.net.netty.test.proto.Packet1Wapper.internal_static_Packet1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return next.net.netty.test.proto.Packet1Wapper.internal_static_Packet1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                next.net.netty.test.proto.Packet1Wapper.Packet1.class, next.net.netty.test.proto.Packet1Wapper.Packet1.Builder.class);
      }

      // Construct using next.net.netty.test.proto.Packet1Wapper.Packet1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = 0;

        money_ = 0;

        time_ = 0L;

        vip_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return next.net.netty.test.proto.Packet1Wapper.internal_static_Packet1_descriptor;
      }

      public next.net.netty.test.proto.Packet1Wapper.Packet1 getDefaultInstanceForType() {
        return next.net.netty.test.proto.Packet1Wapper.Packet1.getDefaultInstance();
      }

      public next.net.netty.test.proto.Packet1Wapper.Packet1 build() {
        next.net.netty.test.proto.Packet1Wapper.Packet1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public next.net.netty.test.proto.Packet1Wapper.Packet1 buildPartial() {
        next.net.netty.test.proto.Packet1Wapper.Packet1 result = new next.net.netty.test.proto.Packet1Wapper.Packet1(this);
        result.playerId_ = playerId_;
        result.money_ = money_;
        result.time_ = time_;
        result.vip_ = vip_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof next.net.netty.test.proto.Packet1Wapper.Packet1) {
          return mergeFrom((next.net.netty.test.proto.Packet1Wapper.Packet1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(next.net.netty.test.proto.Packet1Wapper.Packet1 other) {
        if (other == next.net.netty.test.proto.Packet1Wapper.Packet1.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getMoney() != 0) {
          setMoney(other.getMoney());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getVip() != false) {
          setVip(other.getVip());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        next.net.netty.test.proto.Packet1Wapper.Packet1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (next.net.netty.test.proto.Packet1Wapper.Packet1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerId_ ;
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int money_ ;
      /**
       * <code>optional int32 money = 2;</code>
       */
      public int getMoney() {
        return money_;
      }
      /**
       * <code>optional int32 money = 2;</code>
       */
      public Builder setMoney(int value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 money = 2;</code>
       */
      public Builder clearMoney() {
        
        money_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 4;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private boolean vip_ ;
      /**
       * <code>optional bool vip = 3;</code>
       */
      public boolean getVip() {
        return vip_;
      }
      /**
       * <code>optional bool vip = 3;</code>
       */
      public Builder setVip(boolean value) {
        
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool vip = 3;</code>
       */
      public Builder clearVip() {
        
        vip_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Packet1)
    }

    // @@protoc_insertion_point(class_scope:Packet1)
    private static final next.net.netty.test.proto.Packet1Wapper.Packet1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new next.net.netty.test.proto.Packet1Wapper.Packet1();
    }

    public static next.net.netty.test.proto.Packet1Wapper.Packet1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet1>
        PARSER = new com.google.protobuf.AbstractParser<Packet1>() {
      public Packet1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Packet1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet1> getParserForType() {
      return PARSER;
    }

    public next.net.netty.test.proto.Packet1Wapper.Packet1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPacket1.proto\"E\n\007Packet1\022\020\n\010playerId\030\001" +
      " \001(\005\022\r\n\005money\030\002 \001(\005\022\014\n\004time\030\004 \001(\003\022\013\n\003vip" +
      "\030\003 \001(\010B>\n\031next.net.netty.test.protoB\rPac" +
      "ket1Wapper\252\002\021next.client.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Packet1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet1_descriptor,
        new java.lang.String[] { "PlayerId", "Money", "Time", "Vip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
