// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _CorePacket.proto

package packet._core;

public final class CorePacketWapper {
  private CorePacketWapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CorePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CorePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    java.util.List<java.lang.Integer> getTypeList();
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    int getTypeCount();
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    int getType(int index);

    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    boolean hasPing();
    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    packet.ping.PingWapper.Ping getPing();
    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    packet.ping.PingWapper.PingOrBuilder getPingOrBuilder();

    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    boolean hasPong();
    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    packet.ping.PingWapper.Pong getPong();
    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    packet.ping.PingWapper.PongOrBuilder getPongOrBuilder();
  }
  /**
   * Protobuf type {@code CorePacket}
   */
  public  static final class CorePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CorePacket)
      CorePacketOrBuilder {
    // Use CorePacket.newBuilder() to construct.
    private CorePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CorePacket() {
      type_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CorePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              type_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                type_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 810: {
              packet.ping.PingWapper.Ping.Builder subBuilder = null;
              if (ping_ != null) {
                subBuilder = ping_.toBuilder();
              }
              ping_ = input.readMessage(packet.ping.PingWapper.Ping.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ping_);
                ping_ = subBuilder.buildPartial();
              }

              break;
            }
            case 818: {
              packet.ping.PingWapper.Pong.Builder subBuilder = null;
              if (pong_ != null) {
                subBuilder = pong_.toBuilder();
              }
              pong_ = input.readMessage(packet.ping.PingWapper.Pong.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pong_);
                pong_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet._core.CorePacketWapper.internal_static_CorePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet._core.CorePacketWapper.CorePacket.class, packet._core.CorePacketWapper.CorePacket.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> type_;
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getTypeList() {
      return type_;
    }
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public int getType(int index) {
      return type_.get(index);
    }
    private int typeMemoizedSerializedSize = -1;

    public static final int PING_FIELD_NUMBER = 101;
    private packet.ping.PingWapper.Ping ping_;
    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    public boolean hasPing() {
      return ping_ != null;
    }
    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    public packet.ping.PingWapper.Ping getPing() {
      return ping_ == null ? packet.ping.PingWapper.Ping.getDefaultInstance() : ping_;
    }
    /**
     * <code>optional .Ping Ping = 101;</code>
     */
    public packet.ping.PingWapper.PingOrBuilder getPingOrBuilder() {
      return getPing();
    }

    public static final int PONG_FIELD_NUMBER = 102;
    private packet.ping.PingWapper.Pong pong_;
    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    public boolean hasPong() {
      return pong_ != null;
    }
    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    public packet.ping.PingWapper.Pong getPong() {
      return pong_ == null ? packet.ping.PingWapper.Pong.getDefaultInstance() : pong_;
    }
    /**
     * <code>optional .Pong Pong = 102;</code>
     */
    public packet.ping.PingWapper.PongOrBuilder getPongOrBuilder() {
      return getPong();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getTypeList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(typeMemoizedSerializedSize);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeInt32NoTag(type_.get(i));
      }
      if (ping_ != null) {
        output.writeMessage(101, getPing());
      }
      if (pong_ != null) {
        output.writeMessage(102, getPong());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(type_.get(i));
        }
        size += dataSize;
        if (!getTypeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        typeMemoizedSerializedSize = dataSize;
      }
      if (ping_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, getPing());
      }
      if (pong_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, getPong());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet._core.CorePacketWapper.CorePacket)) {
        return super.equals(obj);
      }
      packet._core.CorePacketWapper.CorePacket other = (packet._core.CorePacketWapper.CorePacket) obj;

      boolean result = true;
      result = result && getTypeList()
          .equals(other.getTypeList());
      result = result && (hasPing() == other.hasPing());
      if (hasPing()) {
        result = result && getPing()
            .equals(other.getPing());
      }
      result = result && (hasPong() == other.hasPong());
      if (hasPong()) {
        result = result && getPong()
            .equals(other.getPong());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTypeList().hashCode();
      }
      if (hasPing()) {
        hash = (37 * hash) + PING_FIELD_NUMBER;
        hash = (53 * hash) + getPing().hashCode();
      }
      if (hasPong()) {
        hash = (37 * hash) + PONG_FIELD_NUMBER;
        hash = (53 * hash) + getPong().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet._core.CorePacketWapper.CorePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CorePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CorePacket)
        packet._core.CorePacketWapper.CorePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet._core.CorePacketWapper.CorePacket.class, packet._core.CorePacketWapper.CorePacket.Builder.class);
      }

      // Construct using packet._core.CorePacketWapper.CorePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pingBuilder_ == null) {
          ping_ = null;
        } else {
          ping_ = null;
          pingBuilder_ = null;
        }
        if (pongBuilder_ == null) {
          pong_ = null;
        } else {
          pong_ = null;
          pongBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
      }

      public packet._core.CorePacketWapper.CorePacket getDefaultInstanceForType() {
        return packet._core.CorePacketWapper.CorePacket.getDefaultInstance();
      }

      public packet._core.CorePacketWapper.CorePacket build() {
        packet._core.CorePacketWapper.CorePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet._core.CorePacketWapper.CorePacket buildPartial() {
        packet._core.CorePacketWapper.CorePacket result = new packet._core.CorePacketWapper.CorePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.type_ = type_;
        if (pingBuilder_ == null) {
          result.ping_ = ping_;
        } else {
          result.ping_ = pingBuilder_.build();
        }
        if (pongBuilder_ == null) {
          result.pong_ = pong_;
        } else {
          result.pong_ = pongBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet._core.CorePacketWapper.CorePacket) {
          return mergeFrom((packet._core.CorePacketWapper.CorePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet._core.CorePacketWapper.CorePacket other) {
        if (other == packet._core.CorePacketWapper.CorePacket.getDefaultInstance()) return this;
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        if (other.hasPong()) {
          mergePong(other.getPong());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet._core.CorePacketWapper.CorePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet._core.CorePacketWapper.CorePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> type_ = java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = new java.util.ArrayList<java.lang.Integer>(type_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public int getType(int index) {
        return type_.get(index);
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder setType(
          int index, int value) {
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder addType(int value) {
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, type_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private packet.ping.PingWapper.Ping ping_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.ping.PingWapper.Ping, packet.ping.PingWapper.Ping.Builder, packet.ping.PingWapper.PingOrBuilder> pingBuilder_;
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public boolean hasPing() {
        return pingBuilder_ != null || ping_ != null;
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public packet.ping.PingWapper.Ping getPing() {
        if (pingBuilder_ == null) {
          return ping_ == null ? packet.ping.PingWapper.Ping.getDefaultInstance() : ping_;
        } else {
          return pingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public Builder setPing(packet.ping.PingWapper.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ping_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public Builder setPing(
          packet.ping.PingWapper.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          ping_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public Builder mergePing(packet.ping.PingWapper.Ping value) {
        if (pingBuilder_ == null) {
          if (ping_ != null) {
            ping_ =
              packet.ping.PingWapper.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
          } else {
            ping_ = value;
          }
          onChanged();
        } else {
          pingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          ping_ = null;
          onChanged();
        } else {
          ping_ = null;
          pingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public packet.ping.PingWapper.Ping.Builder getPingBuilder() {
        
        onChanged();
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      public packet.ping.PingWapper.PingOrBuilder getPingOrBuilder() {
        if (pingBuilder_ != null) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          return ping_ == null ?
              packet.ping.PingWapper.Ping.getDefaultInstance() : ping_;
        }
      }
      /**
       * <code>optional .Ping Ping = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.ping.PingWapper.Ping, packet.ping.PingWapper.Ping.Builder, packet.ping.PingWapper.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.ping.PingWapper.Ping, packet.ping.PingWapper.Ping.Builder, packet.ping.PingWapper.PingOrBuilder>(
                  getPing(),
                  getParentForChildren(),
                  isClean());
          ping_ = null;
        }
        return pingBuilder_;
      }

      private packet.ping.PingWapper.Pong pong_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.ping.PingWapper.Pong, packet.ping.PingWapper.Pong.Builder, packet.ping.PingWapper.PongOrBuilder> pongBuilder_;
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public boolean hasPong() {
        return pongBuilder_ != null || pong_ != null;
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public packet.ping.PingWapper.Pong getPong() {
        if (pongBuilder_ == null) {
          return pong_ == null ? packet.ping.PingWapper.Pong.getDefaultInstance() : pong_;
        } else {
          return pongBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public Builder setPong(packet.ping.PingWapper.Pong value) {
        if (pongBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pong_ = value;
          onChanged();
        } else {
          pongBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public Builder setPong(
          packet.ping.PingWapper.Pong.Builder builderForValue) {
        if (pongBuilder_ == null) {
          pong_ = builderForValue.build();
          onChanged();
        } else {
          pongBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public Builder mergePong(packet.ping.PingWapper.Pong value) {
        if (pongBuilder_ == null) {
          if (pong_ != null) {
            pong_ =
              packet.ping.PingWapper.Pong.newBuilder(pong_).mergeFrom(value).buildPartial();
          } else {
            pong_ = value;
          }
          onChanged();
        } else {
          pongBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public Builder clearPong() {
        if (pongBuilder_ == null) {
          pong_ = null;
          onChanged();
        } else {
          pong_ = null;
          pongBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public packet.ping.PingWapper.Pong.Builder getPongBuilder() {
        
        onChanged();
        return getPongFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      public packet.ping.PingWapper.PongOrBuilder getPongOrBuilder() {
        if (pongBuilder_ != null) {
          return pongBuilder_.getMessageOrBuilder();
        } else {
          return pong_ == null ?
              packet.ping.PingWapper.Pong.getDefaultInstance() : pong_;
        }
      }
      /**
       * <code>optional .Pong Pong = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.ping.PingWapper.Pong, packet.ping.PingWapper.Pong.Builder, packet.ping.PingWapper.PongOrBuilder> 
          getPongFieldBuilder() {
        if (pongBuilder_ == null) {
          pongBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.ping.PingWapper.Pong, packet.ping.PingWapper.Pong.Builder, packet.ping.PingWapper.PongOrBuilder>(
                  getPong(),
                  getParentForChildren(),
                  isClean());
          pong_ = null;
        }
        return pongBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CorePacket)
    }

    // @@protoc_insertion_point(class_scope:CorePacket)
    private static final packet._core.CorePacketWapper.CorePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet._core.CorePacketWapper.CorePacket();
    }

    public static packet._core.CorePacketWapper.CorePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CorePacket>
        PARSER = new com.google.protobuf.AbstractParser<CorePacket>() {
      public CorePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CorePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CorePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CorePacket> getParserForType() {
      return PARSER;
    }

    public packet._core.CorePacketWapper.CorePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CorePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CorePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021_CorePacket.proto\032\nPing.proto\"D\n\nCoreP" +
      "acket\022\014\n\004type\030\001 \003(\005\022\023\n\004Ping\030e \001(\0132\005.Ping" +
      "\022\023\n\004Pong\030f \001(\0132\005.PongB/\n\014packet._coreB\020C" +
      "orePacketWapper\252\002\014packet._coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          packet.ping.PingWapper.getDescriptor(),
        }, assigner);
    internal_static_CorePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CorePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CorePacket_descriptor,
        new java.lang.String[] { "Type", "Ping", "Pong", });
    packet.ping.PingWapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
