// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _CorePacket.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace packet._core {

  /// <summary>Holder for reflection information generated from _CorePacket.proto</summary>
  public static partial class CorePacketReflection {

    #region Descriptor
    /// <summary>File descriptor for _CorePacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CorePacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFfQ29yZVBhY2tldC5wcm90bxoKUGluZy5wcm90byJECgpDb3JlUGFja2V0",
            "EgwKBHR5cGUYASADKAUSEwoEUGluZxhlIAEoCzIFLlBpbmcSEwoEUG9uZxhm",
            "IAEoCzIFLlBvbmdCLwoMcGFja2V0Ll9jb3JlQhBDb3JlUGFja2V0V2FwcGVy",
            "qgIMcGFja2V0Ll9jb3JlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::packet.ping.PingReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::packet._core.CorePacket), global::packet._core.CorePacket.Parser, new[]{ "Type", "Ping", "Pong" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CorePacket : pb::IMessage<CorePacket> {
    private static readonly pb::MessageParser<CorePacket> _parser = new pb::MessageParser<CorePacket>(() => new CorePacket());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CorePacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::packet._core.CorePacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CorePacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CorePacket(CorePacket other) : this() {
      type_ = other.type_.Clone();
      Ping = other.ping_ != null ? other.Ping.Clone() : null;
      Pong = other.pong_ != null ? other.Pong.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CorePacket Clone() {
      return new CorePacket(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_type_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> type_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///  內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Type {
      get { return type_; }
    }

    /// <summary>Field number for the "Ping" field.</summary>
    public const int PingFieldNumber = 101;
    private global::packet.ping.Ping ping_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::packet.ping.Ping Ping {
      get { return ping_; }
      set {
        ping_ = value;
      }
    }

    /// <summary>Field number for the "Pong" field.</summary>
    public const int PongFieldNumber = 102;
    private global::packet.ping.Pong pong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::packet.ping.Pong Pong {
      get { return pong_; }
      set {
        pong_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CorePacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CorePacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!type_.Equals(other.type_)) return false;
      if (!object.Equals(Ping, other.Ping)) return false;
      if (!object.Equals(Pong, other.Pong)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= type_.GetHashCode();
      if (ping_ != null) hash ^= Ping.GetHashCode();
      if (pong_ != null) hash ^= Pong.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      type_.WriteTo(output, _repeated_type_codec);
      if (ping_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Ping);
      }
      if (pong_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Pong);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += type_.CalculateSize(_repeated_type_codec);
      if (ping_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Ping);
      }
      if (pong_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Pong);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CorePacket other) {
      if (other == null) {
        return;
      }
      type_.Add(other.type_);
      if (other.ping_ != null) {
        if (ping_ == null) {
          ping_ = new global::packet.ping.Ping();
        }
        Ping.MergeFrom(other.Ping);
      }
      if (other.pong_ != null) {
        if (pong_ == null) {
          pong_ = new global::packet.ping.Pong();
        }
        Pong.MergeFrom(other.Pong);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            type_.AddEntriesFrom(input, _repeated_type_codec);
            break;
          }
          case 810: {
            if (ping_ == null) {
              ping_ = new global::packet.ping.Ping();
            }
            input.ReadMessage(ping_);
            break;
          }
          case 818: {
            if (pong_ == null) {
              pong_ = new global::packet.ping.Pong();
            }
            input.ReadMessage(pong_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
