// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketCore.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace next.client.proto {

  /// <summary>Holder for reflection information generated from PacketCore.proto</summary>
  public static partial class PacketCoreReflection {

    #region Descriptor
    /// <summary>File descriptor for PacketCore.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketCoreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQYWNrZXRDb3JlLnByb3RvGg1QYWNrZXQxLnByb3RvGg1QYWNrZXQyLnBy",
            "b3RvIlAKClBhY2tldENvcmUSDAoEdHlwZRgBIAMoBRIZCgdQYWNrZXQxGGUg",
            "ASgLMgguUGFja2V0MRIZCgdQYWNrZXQyGGYgASgLMgguUGFja2V0MkJBChlu",
            "ZXh0Lm5ldC5uZXR0eS50ZXN0LnByb3RvQhBQYWNrZXRDb3JlV2FwcGVyqgIR",
            "bmV4dC5jbGllbnQucHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::next.client.proto.Packet1Reflection.Descriptor, global::next.client.proto.Packet2Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::next.client.proto.PacketCore), global::next.client.proto.PacketCore.Parser, new[]{ "Type", "Packet1", "Packet2" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PacketCore : pb::IMessage<PacketCore> {
    private static readonly pb::MessageParser<PacketCore> _parser = new pb::MessageParser<PacketCore>(() => new PacketCore());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PacketCore> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::next.client.proto.PacketCoreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketCore() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketCore(PacketCore other) : this() {
      type_ = other.type_.Clone();
      Packet1 = other.packet1_ != null ? other.Packet1.Clone() : null;
      Packet2 = other.packet2_ != null ? other.Packet2.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketCore Clone() {
      return new PacketCore(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_type_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> type_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Type {
      get { return type_; }
    }

    /// <summary>Field number for the "Packet1" field.</summary>
    public const int Packet1FieldNumber = 101;
    private global::next.client.proto.Packet1 packet1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::next.client.proto.Packet1 Packet1 {
      get { return packet1_; }
      set {
        packet1_ = value;
      }
    }

    /// <summary>Field number for the "Packet2" field.</summary>
    public const int Packet2FieldNumber = 102;
    private global::next.client.proto.Packet2 packet2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::next.client.proto.Packet2 Packet2 {
      get { return packet2_; }
      set {
        packet2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PacketCore);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PacketCore other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!type_.Equals(other.type_)) return false;
      if (!object.Equals(Packet1, other.Packet1)) return false;
      if (!object.Equals(Packet2, other.Packet2)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= type_.GetHashCode();
      if (packet1_ != null) hash ^= Packet1.GetHashCode();
      if (packet2_ != null) hash ^= Packet2.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      type_.WriteTo(output, _repeated_type_codec);
      if (packet1_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Packet1);
      }
      if (packet2_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Packet2);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += type_.CalculateSize(_repeated_type_codec);
      if (packet1_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Packet1);
      }
      if (packet2_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Packet2);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PacketCore other) {
      if (other == null) {
        return;
      }
      type_.Add(other.type_);
      if (other.packet1_ != null) {
        if (packet1_ == null) {
          packet1_ = new global::next.client.proto.Packet1();
        }
        Packet1.MergeFrom(other.Packet1);
      }
      if (other.packet2_ != null) {
        if (packet2_ == null) {
          packet2_ = new global::next.client.proto.Packet2();
        }
        Packet2.MergeFrom(other.Packet2);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            type_.AddEntriesFrom(input, _repeated_type_codec);
            break;
          }
          case 810: {
            if (packet1_ == null) {
              packet1_ = new global::next.client.proto.Packet1();
            }
            input.ReadMessage(packet1_);
            break;
          }
          case 818: {
            if (packet2_ == null) {
              packet2_ = new global::next.client.proto.Packet2();
            }
            input.ReadMessage(packet2_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
