// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _CorePacket.proto

package packet._core;

public final class CorePacketWapper {
  private CorePacketWapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CorePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CorePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    java.util.List<java.lang.Integer> getTypeList();
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    int getTypeCount();
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    int getType(int index);

    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    boolean hasSimple1();
    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    packet.simple.SimpleWapper.Simple1 getSimple1();
    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    packet.simple.SimpleWapper.Simple1OrBuilder getSimple1OrBuilder();

    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    boolean hasSimple2();
    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    packet.simple.SimpleWapper.Simple2 getSimple2();
    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    packet.simple.SimpleWapper.Simple2OrBuilder getSimple2OrBuilder();
  }
  /**
   * Protobuf type {@code CorePacket}
   */
  public  static final class CorePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CorePacket)
      CorePacketOrBuilder {
    // Use CorePacket.newBuilder() to construct.
    private CorePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CorePacket() {
      type_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CorePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              type_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                type_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 810: {
              packet.simple.SimpleWapper.Simple1.Builder subBuilder = null;
              if (simple1_ != null) {
                subBuilder = simple1_.toBuilder();
              }
              simple1_ = input.readMessage(packet.simple.SimpleWapper.Simple1.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simple1_);
                simple1_ = subBuilder.buildPartial();
              }

              break;
            }
            case 818: {
              packet.simple.SimpleWapper.Simple2.Builder subBuilder = null;
              if (simple2_ != null) {
                subBuilder = simple2_.toBuilder();
              }
              simple2_ = input.readMessage(packet.simple.SimpleWapper.Simple2.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simple2_);
                simple2_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet._core.CorePacketWapper.internal_static_CorePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet._core.CorePacketWapper.CorePacket.class, packet._core.CorePacketWapper.CorePacket.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> type_;
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getTypeList() {
      return type_;
    }
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <pre>
     * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
     * </pre>
     *
     * <code>repeated int32 type = 1;</code>
     */
    public int getType(int index) {
      return type_.get(index);
    }
    private int typeMemoizedSerializedSize = -1;

    public static final int SIMPLE1_FIELD_NUMBER = 101;
    private packet.simple.SimpleWapper.Simple1 simple1_;
    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    public boolean hasSimple1() {
      return simple1_ != null;
    }
    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    public packet.simple.SimpleWapper.Simple1 getSimple1() {
      return simple1_ == null ? packet.simple.SimpleWapper.Simple1.getDefaultInstance() : simple1_;
    }
    /**
     * <pre>
     * 範例封包
     * </pre>
     *
     * <code>optional .Simple1 Simple1 = 101;</code>
     */
    public packet.simple.SimpleWapper.Simple1OrBuilder getSimple1OrBuilder() {
      return getSimple1();
    }

    public static final int SIMPLE2_FIELD_NUMBER = 102;
    private packet.simple.SimpleWapper.Simple2 simple2_;
    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    public boolean hasSimple2() {
      return simple2_ != null;
    }
    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    public packet.simple.SimpleWapper.Simple2 getSimple2() {
      return simple2_ == null ? packet.simple.SimpleWapper.Simple2.getDefaultInstance() : simple2_;
    }
    /**
     * <code>optional .Simple2 Simple2 = 102;</code>
     */
    public packet.simple.SimpleWapper.Simple2OrBuilder getSimple2OrBuilder() {
      return getSimple2();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getTypeList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(typeMemoizedSerializedSize);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeInt32NoTag(type_.get(i));
      }
      if (simple1_ != null) {
        output.writeMessage(101, getSimple1());
      }
      if (simple2_ != null) {
        output.writeMessage(102, getSimple2());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(type_.get(i));
        }
        size += dataSize;
        if (!getTypeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        typeMemoizedSerializedSize = dataSize;
      }
      if (simple1_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, getSimple1());
      }
      if (simple2_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, getSimple2());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof packet._core.CorePacketWapper.CorePacket)) {
        return super.equals(obj);
      }
      packet._core.CorePacketWapper.CorePacket other = (packet._core.CorePacketWapper.CorePacket) obj;

      boolean result = true;
      result = result && getTypeList()
          .equals(other.getTypeList());
      result = result && (hasSimple1() == other.hasSimple1());
      if (hasSimple1()) {
        result = result && getSimple1()
            .equals(other.getSimple1());
      }
      result = result && (hasSimple2() == other.hasSimple2());
      if (hasSimple2()) {
        result = result && getSimple2()
            .equals(other.getSimple2());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTypeList().hashCode();
      }
      if (hasSimple1()) {
        hash = (37 * hash) + SIMPLE1_FIELD_NUMBER;
        hash = (53 * hash) + getSimple1().hashCode();
      }
      if (hasSimple2()) {
        hash = (37 * hash) + SIMPLE2_FIELD_NUMBER;
        hash = (53 * hash) + getSimple2().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static packet._core.CorePacketWapper.CorePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(packet._core.CorePacketWapper.CorePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CorePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CorePacket)
        packet._core.CorePacketWapper.CorePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet._core.CorePacketWapper.CorePacket.class, packet._core.CorePacketWapper.CorePacket.Builder.class);
      }

      // Construct using packet._core.CorePacketWapper.CorePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (simple1Builder_ == null) {
          simple1_ = null;
        } else {
          simple1_ = null;
          simple1Builder_ = null;
        }
        if (simple2Builder_ == null) {
          simple2_ = null;
        } else {
          simple2_ = null;
          simple2Builder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet._core.CorePacketWapper.internal_static_CorePacket_descriptor;
      }

      public packet._core.CorePacketWapper.CorePacket getDefaultInstanceForType() {
        return packet._core.CorePacketWapper.CorePacket.getDefaultInstance();
      }

      public packet._core.CorePacketWapper.CorePacket build() {
        packet._core.CorePacketWapper.CorePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet._core.CorePacketWapper.CorePacket buildPartial() {
        packet._core.CorePacketWapper.CorePacket result = new packet._core.CorePacketWapper.CorePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.type_ = type_;
        if (simple1Builder_ == null) {
          result.simple1_ = simple1_;
        } else {
          result.simple1_ = simple1Builder_.build();
        }
        if (simple2Builder_ == null) {
          result.simple2_ = simple2_;
        } else {
          result.simple2_ = simple2Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet._core.CorePacketWapper.CorePacket) {
          return mergeFrom((packet._core.CorePacketWapper.CorePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet._core.CorePacketWapper.CorePacket other) {
        if (other == packet._core.CorePacketWapper.CorePacket.getDefaultInstance()) return this;
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        if (other.hasSimple1()) {
          mergeSimple1(other.getSimple1());
        }
        if (other.hasSimple2()) {
          mergeSimple2(other.getSimple2());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet._core.CorePacketWapper.CorePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet._core.CorePacketWapper.CorePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> type_ = java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = new java.util.ArrayList<java.lang.Integer>(type_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public int getType(int index) {
        return type_.get(index);
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder setType(
          int index, int value) {
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder addType(int value) {
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, type_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 內存封包編號, 此項不可更名, 型態不可變動, 編號不可變動
       * </pre>
       *
       * <code>repeated int32 type = 1;</code>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private packet.simple.SimpleWapper.Simple1 simple1_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.simple.SimpleWapper.Simple1, packet.simple.SimpleWapper.Simple1.Builder, packet.simple.SimpleWapper.Simple1OrBuilder> simple1Builder_;
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public boolean hasSimple1() {
        return simple1Builder_ != null || simple1_ != null;
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public packet.simple.SimpleWapper.Simple1 getSimple1() {
        if (simple1Builder_ == null) {
          return simple1_ == null ? packet.simple.SimpleWapper.Simple1.getDefaultInstance() : simple1_;
        } else {
          return simple1Builder_.getMessage();
        }
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public Builder setSimple1(packet.simple.SimpleWapper.Simple1 value) {
        if (simple1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simple1_ = value;
          onChanged();
        } else {
          simple1Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public Builder setSimple1(
          packet.simple.SimpleWapper.Simple1.Builder builderForValue) {
        if (simple1Builder_ == null) {
          simple1_ = builderForValue.build();
          onChanged();
        } else {
          simple1Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public Builder mergeSimple1(packet.simple.SimpleWapper.Simple1 value) {
        if (simple1Builder_ == null) {
          if (simple1_ != null) {
            simple1_ =
              packet.simple.SimpleWapper.Simple1.newBuilder(simple1_).mergeFrom(value).buildPartial();
          } else {
            simple1_ = value;
          }
          onChanged();
        } else {
          simple1Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public Builder clearSimple1() {
        if (simple1Builder_ == null) {
          simple1_ = null;
          onChanged();
        } else {
          simple1_ = null;
          simple1Builder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public packet.simple.SimpleWapper.Simple1.Builder getSimple1Builder() {
        
        onChanged();
        return getSimple1FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      public packet.simple.SimpleWapper.Simple1OrBuilder getSimple1OrBuilder() {
        if (simple1Builder_ != null) {
          return simple1Builder_.getMessageOrBuilder();
        } else {
          return simple1_ == null ?
              packet.simple.SimpleWapper.Simple1.getDefaultInstance() : simple1_;
        }
      }
      /**
       * <pre>
       * 範例封包
       * </pre>
       *
       * <code>optional .Simple1 Simple1 = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.simple.SimpleWapper.Simple1, packet.simple.SimpleWapper.Simple1.Builder, packet.simple.SimpleWapper.Simple1OrBuilder> 
          getSimple1FieldBuilder() {
        if (simple1Builder_ == null) {
          simple1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.simple.SimpleWapper.Simple1, packet.simple.SimpleWapper.Simple1.Builder, packet.simple.SimpleWapper.Simple1OrBuilder>(
                  getSimple1(),
                  getParentForChildren(),
                  isClean());
          simple1_ = null;
        }
        return simple1Builder_;
      }

      private packet.simple.SimpleWapper.Simple2 simple2_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.simple.SimpleWapper.Simple2, packet.simple.SimpleWapper.Simple2.Builder, packet.simple.SimpleWapper.Simple2OrBuilder> simple2Builder_;
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public boolean hasSimple2() {
        return simple2Builder_ != null || simple2_ != null;
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public packet.simple.SimpleWapper.Simple2 getSimple2() {
        if (simple2Builder_ == null) {
          return simple2_ == null ? packet.simple.SimpleWapper.Simple2.getDefaultInstance() : simple2_;
        } else {
          return simple2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public Builder setSimple2(packet.simple.SimpleWapper.Simple2 value) {
        if (simple2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simple2_ = value;
          onChanged();
        } else {
          simple2Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public Builder setSimple2(
          packet.simple.SimpleWapper.Simple2.Builder builderForValue) {
        if (simple2Builder_ == null) {
          simple2_ = builderForValue.build();
          onChanged();
        } else {
          simple2Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public Builder mergeSimple2(packet.simple.SimpleWapper.Simple2 value) {
        if (simple2Builder_ == null) {
          if (simple2_ != null) {
            simple2_ =
              packet.simple.SimpleWapper.Simple2.newBuilder(simple2_).mergeFrom(value).buildPartial();
          } else {
            simple2_ = value;
          }
          onChanged();
        } else {
          simple2Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public Builder clearSimple2() {
        if (simple2Builder_ == null) {
          simple2_ = null;
          onChanged();
        } else {
          simple2_ = null;
          simple2Builder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public packet.simple.SimpleWapper.Simple2.Builder getSimple2Builder() {
        
        onChanged();
        return getSimple2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      public packet.simple.SimpleWapper.Simple2OrBuilder getSimple2OrBuilder() {
        if (simple2Builder_ != null) {
          return simple2Builder_.getMessageOrBuilder();
        } else {
          return simple2_ == null ?
              packet.simple.SimpleWapper.Simple2.getDefaultInstance() : simple2_;
        }
      }
      /**
       * <code>optional .Simple2 Simple2 = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          packet.simple.SimpleWapper.Simple2, packet.simple.SimpleWapper.Simple2.Builder, packet.simple.SimpleWapper.Simple2OrBuilder> 
          getSimple2FieldBuilder() {
        if (simple2Builder_ == null) {
          simple2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              packet.simple.SimpleWapper.Simple2, packet.simple.SimpleWapper.Simple2.Builder, packet.simple.SimpleWapper.Simple2OrBuilder>(
                  getSimple2(),
                  getParentForChildren(),
                  isClean());
          simple2_ = null;
        }
        return simple2Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CorePacket)
    }

    // @@protoc_insertion_point(class_scope:CorePacket)
    private static final packet._core.CorePacketWapper.CorePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new packet._core.CorePacketWapper.CorePacket();
    }

    public static packet._core.CorePacketWapper.CorePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CorePacket>
        PARSER = new com.google.protobuf.AbstractParser<CorePacket>() {
      public CorePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CorePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CorePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CorePacket> getParserForType() {
      return PARSER;
    }

    public packet._core.CorePacketWapper.CorePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CorePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CorePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021_CorePacket.proto\032\014Simple.proto\"P\n\nCor" +
      "ePacket\022\014\n\004type\030\001 \003(\005\022\031\n\007Simple1\030e \001(\0132\010" +
      ".Simple1\022\031\n\007Simple2\030f \001(\0132\010.Simple2B/\n\014p" +
      "acket._coreB\020CorePacketWapper\252\002\014packet._" +
      "coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          packet.simple.SimpleWapper.getDescriptor(),
        }, assigner);
    internal_static_CorePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CorePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CorePacket_descriptor,
        new java.lang.String[] { "Type", "Simple1", "Simple2", });
    packet.simple.SimpleWapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
